name: Test Addon

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
    
    - name: Download Blender
      run: |
        mkdir -p tmp
        cd tmp
        wget https://download.blender.org/release/Blender3.6/blender-3.6.0-linux-x64.tar.xz
        tar -xf blender-3.6.0-linux-x64.tar.xz
        echo "BLENDER_PATH=$PWD/blender-3.6.0-linux-x64/blender" >> $GITHUB_ENV
    
    - name: Build addon
      run: |
        python build.py --version test
        echo "ADDON_PATH=$PWD/dist/multi_channel_export_test.zip" >> $GITHUB_ENV
    
    - name: Run basic addon loading test
      run: |
        $BLENDER_PATH -b --python-expr "import sys; sys.path.append('tests'); import test_load_addon; test_load_addon.run('$ADDON_PATH')"
    
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint addon --fail-under=7
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: addon-zip
        path: dist/*.zip